# For a description of configuration options, see
# https://www.streetsidesoftware.com/vscode-spell-checker/docs/configuration/
# cSpell:ignore textlint textlintrc
version: '0.2'
caseSensitive: true
ignorePaths:
  - '*.svg'
  - node_modules
  - public
  - tmp
patterns:
  - name: CodeBlock
    pattern: |
      /
          ^(\s*[~`]{3,})   # code-block start
          .*               # all languages and options, e.g. shell {hl_lines=[12]}
          [\s\S]*?         # content
          \1               # code-block end - cSpell:disable-next-line
      /igmx
languageSettings:
  - languageId: markdown
    ignoreRegExpList:
      - CodeBlock
dictionaryDefinitions:
  - name: project-words
    path: .cspell/project-words.txt
  - name: project-names
    path: .cspell/project-names.g.txt
dictionaries:
  - project-words
  - project-names
