DirectoryPath: public
CheckExternal: false
IgnoreAltMissing: true
IgnoreInternalEmptyHash: true
IgnoreURLs:
  - ^/docs/latest(/?|/architecture/)$
  - /livereload.js # cSpell:disable-line
  # Valid URL, whether canonical (before reorg) or not (and handled via a redirect)
  - ^/docs/1.[6-9]\d/
  - ^\.\./\.\./sampling/
