DirectoryPath: public
IgnoreDirectoryMissingTrailingSlash: true
CheckExternal: false
IgnoreAltMissing: true
IgnoreURLs:
  - /livereload.js
  - ^/docs/latest/ # ignore redirect of latest
  - ^/docs/1.69/client-(features|libraries)/
