sudo: required
language: minimal
dist: trusty
git:
  # pull everything for safe commits comparison before deploying
  depth: false
env:
  global:
  # GH_TOKEN
  - secure: "wG1CCMJbXofnP/tOxv4YC6z82cC23VoJL2Ui6meOT+AFnZSI7W8trL9mEO1lgRNQp18+IjDVZLDilIFCHXWIW/Wc8pqoWYCuSRIjt+YEdT3w2NYEWm6L02cdhKe+fbYGaISLdTV2Il2POVnecgvufkqcSPex9sLqikuPe6OnVI5mmyyq98U0Tzx0Kkk8m2erKGZDFKCLSQ1jPKbbRvZm+l+clNgiqYp9CgqGRMNSHnNho0t9gV5rgF6kfR9N+p1ifrPHfGXL1xb3uiwwPg/ZtIiEog+gSDLnTjRuEgFGW4nFstNhu54aOuGYcdEXRbQ/fTqR6FRGegnwVpddalieKOsL22ytCsWTZje0KFFWDv67eQQuUeEfprWloyvLRk8764C/3uPyCVx5Jox+jjn9cWwjP8h0hh8fDi2CyV+hIaT3UNlorTg+33ncKo3tzRN+91NudQVk9rwpbW72DqetjaKPxhqMVtCL/oN2Lc3S5jZSQAS0DijvhZs3CYvU4CpHgJb30Dc8HO5UxFHwhxo/TI7qb7Aj8pw10H/AJdeB8UMuGwTNCKcxrAPoBMnNm6XrqHQfHeL1OcwPJMOwK26fBVvEHWkTudMmDZlsjsvJzYeTaTzEmU0FwAf8uu1mkd4Bdsq3QJI1AeixUwjWL9o2H0Jd0uZY78DBeUWwWpZrgJE="
before_install:
- git config user.name "jaegertracingci"
- git config user.email "jaegertracingci+jaeger-tracing@googlegroups.com"
# setup https authentication credentials, used by ./gradlew publish
- git config credential.helper "store --file=.git/credentials"
- echo "https://$GH_TOKEN:@github.com" > .git/credentials

script:
  - bash ./travis/release.sh
