sudo: required

dist: trusty

language: python

matrix:
  include:
  - python: '2.7.9'

services:
  - docker

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}

install:
  - make bootstrap

script:
  - make build

after_success:
  - echo success
