name: Test
# cSpell:ignore github wjdp

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-check-links:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7

    - uses: actions/setup-node@v7
      with: { node-version-file: .nvmrc }
    - run: npm install
    - name: Build and check links
      run: npm run check:links:all # command also builds the site

  spellcheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    - uses: actions/setup-node@v7
      with: { node-version-file: .nvmrc }
    - run: npm install
    - run: npm run check:spelling

  test-reorg-docs:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: scripts/reorg-docs
    steps:
    - uses: actions/checkout@v7
    - uses: actions/setup-node@v7
      with: { node-version-file: .nvmrc }
    - run: npm install
    - run: npm run build
    - run: npm test -- --runInBand

  block-pr-from-main-branch:
    runs-on: ubuntu-latest
    steps:
    - name: Ensure PR is not on main branch
      uses: jaegertracing/jaeger/.github/actions/block-pr-from-main-branch@main
